name: CI-CD for Databricks Wheel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install setuptools wheel

      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Install Databricks CLI
        run: |
          pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          mkdir -p ~/.databricks
          echo "${{ secrets.DATABRICKS_HOST }}" > /tmp/host_token.txt
          echo "${{ secrets.DATABRICKS_TOKEN }}" >> /tmp/host_token.txt
          cat /tmp/host_token.txt | databricks configure --token

      - name: Upload wheel to DBFS
        run: |
          WHEEL_PATH=$(ls dist/*.whl | head -n 1)
          echo "Uploading wheel: $WHEEL_PATH"
          databricks fs cp "$WHEEL_PATH" "dbfs:/FileStore/wheels/" --overwrite

      - name: Update & run Databricks job
        run: |
          # Grab the wheel filename for the new library path
          WHEEL_FILE=$(ls dist/*.whl | xargs -n1 basename)
          WHEEL_DBFS="dbfs:/FileStore/wheels/$WHEEL_FILE"

          # Create a JSON file with the new wheel path
          cat > job_settings.json <<EOF
{
  "job_id": "946439153829696",
  "new_settings": {
    "tasks": [
      {
        "task_key": "test_job",
        "libraries": [
          {
            "whl": "$WHEEL_DBFS"
          }
        ]
      }
    ]
  }
}
EOF

          # Debug JSON before executing command
          cat job_settings.json
          jq . job_settings.json  # Validate JSON formatting

          # Update and run the Databricks job
          databricks jobs reset --json-file job_settings.json
          databricks jobs run-now --job-id 946439153829696
